# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # NOTE(jkoelker) The nebula plugin requires a git history to walk.
      #                This checks out the entire tree instead of just the
      #                HEAD.
      with:
        fetch-depth: 0
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      # NOTE(jkoelker) Java 8.0.241 and above check certificates that are to
      #                be used as CA certificates for the proper extensions.
      #                Since the tests CA certificates do not have the
      #                correct extensions, pin to 232 that does not have the
      #                checks.
      with:
        java-version: 8.0.232
    - name: Build with Gradle
      run: ./gradlew --info build
